<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0d1f5cc2-0666-4bbb-b22e-3e8371e8525c</testSuiteGuid>
   <testCaseLink>
      <guid>fa4abda4-8571-4d43-8083-911193ddd5e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-01-Login/Login Username Failed - Blocks</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fce6274d-4b48-4480-bd7d-780425389015</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalon data/logininvalid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>fce6274d-4b48-4480-bd7d-780425389015</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8a4c3609-39e5-4a4e-aae7-2a1e96185dbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fce6274d-4b48-4480-bd7d-780425389015</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f16e3775-cc76-471f-a862-1345c363aa9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f61603cc-a9d6-4b33-bb6c-9838e23f90b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-01-Login/Login Password Failed - Blocks</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d1b8dbf2-3e61-42f0-ade8-e1aab3ff4c7d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalon data/logininvalid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d1b8dbf2-3e61-42f0-ade8-e1aab3ff4c7d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>46640f8e-4800-44a8-b90d-31b7ab98abbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d1b8dbf2-3e61-42f0-ade8-e1aab3ff4c7d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5406d07c-2017-4e11-91e2-f4dfa473f6e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8a638f6-4259-4dd9-98fc-47066edf7ea8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-01-Login/Login Success - Blocks</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2746d15d-d2c2-4b69-8ea1-7ec4d77b2473</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalon data/loginvalid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2746d15d-d2c2-4b69-8ea1-7ec4d77b2473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e3aec079-1580-44f9-a77b-e7b58494e4ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2746d15d-d2c2-4b69-8ea1-7ec4d77b2473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1e77b6d8-c3d6-46e9-a37e-afd679768490</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
